server:
  port: 7900 #程序啟動后的端口,也就是 tomcat 的端口,我們可以自己定义
spring:
  application:
    name: provider-user #应用名称,别名
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:1234@localhost:10000/eureka